[package]
name = "text_to_emoji"
version = "0.1.0"
edition = "2024"
author = "Bishal Kunwar Magar"
description = "convert text to emoji"
license = "MIT"
repository = "https://github.com/bishal312/Rust.git"
homepage = "https://github.com/bishal312/Rust.git"
readme = "README.md"
keywords = ["emoji", "text", "convert", "rust"]
categories = [""]

